% Script which defines the global states

global lfp_tfa_states;

lfp_tfa_states.INI_TRI       = 1; % initialize trial
lfp_tfa_states.FIX_ACQ       = 2; % fixation acquisition
lfp_tfa_states.FIX_HOL       = 3; % fixation hold
lfp_tfa_states.TAR_ACQ       = 4; % target acquisition
lfp_tfa_states.TAR_HOL       = 5; % target hold
lfp_tfa_states.CUE_ON        = 6; % cue on
lfp_tfa_states.MEM_PER       = 7; % memory period
lfp_tfa_states.DEL_PER       = 8; % delay period
lfp_tfa_states.TAR_ACQ_INV   = 9; % target acquisition invisible
lfp_tfa_states.TAR_HOL_INV   = 10; % target hold invisible
lfp_tfa_states.MAT_ACQ       = 11; % target acquisition in sample to match
lfp_tfa_states.MAT_HOL       = 12; % target acquisition in sample to match
lfp_tfa_states.MAT_ACQ_MSK   = 13; % target acquisition in sample to match
lfp_tfa_states.MAT_HOL_MSK   = 14; % target acquisition in sample to match
lfp_tfa_states.SEN_RET       = 15; % return to sensors for poffenberger
lfp_tfa_states.ABORT         = 19;
lfp_tfa_states.SUCCESS       = 20;
lfp_tfa_states.REWARD        = 21;
lfp_tfa_states.ITI           = 50;
lfp_tfa_states.SAC_INI       = 60; % saccade start
lfp_tfa_states.SAC_END       = 61;
lfp_tfa_states.REA_INI       = 62; %reach start
lfp_tfa_states.REA_END       = 63;
lfp_tfa_states.TRI_END       = 90;
lfp_tfa_states.ITI_END       = 98;
lfp_tfa_states.CLOSE         = 99;
lfp_tfa_states.SCP_NoState = 1000;
lfp_tfa_states.SCP_InitializeParadigm = 1001;
lfp_tfa_states.SCP_Wait4HandSensors = 1002;
lfp_tfa_states.SCP_InitialHoldDelay = 1003;
lfp_tfa_states.SCP_ShowInitialTargets = 1004;
lfp_tfa_states.SCP_ShowInitialTargetsHold = 1005;
lfp_tfa_states.SCP_TargetRewardDelay = 1009;
lfp_tfa_states.SCP_EvaluateOutcome = 1010;
lfp_tfa_states.SCP_ITI = 1011;
lfp_tfa_states.SCP_Abort = 1012;
lfp_tfa_states.SCP_ShowChoiceTargets = 1013;
lfp_tfa_states.SCP_ShowChoiceTargetsHold = 1014;
lfp_tfa_states.SCP_Tracker_visualisation_visible = 1017;
lfp_tfa_states.SCP_ShowChoiceTargetsIFTHoldDelay = 1021;
lfp_tfa_states.SCP_ShowIntialTargetsBrightenFirst = 1022;
lfp_tfa_states.SCP_ShowChoiceTargetsFirstGo = 1023;
lfp_tfa_states.SCP_ShowChoiceTargetsBrightenFirst = 1025;
lfp_tfa_states.SCP_ShowChoiceTargetsBrightenFirstFirstGo = 1026;
lfp_tfa_states.SCP_ShowTrialTypeCue = 1027;
lfp_tfa_states.SCP_A_HoldReleaseTime_ms = 11001;
lfp_tfa_states.SCP_B_HoldReleaseTime_ms = 11002;
lfp_tfa_states.SCP_A_InitialFixationTouchTime_ms = 11003;
lfp_tfa_states.SCP_B_InitialFixationTouchTime_ms = 11004;
lfp_tfa_states.SCP_A_InitialFixationReleaseTime_ms = 11005;
lfp_tfa_states.SCP_B_InitialFixationReleaseTime_ms = 11006;
lfp_tfa_states.SCP_A_TargetTouchTime_ms = 11007;
lfp_tfa_states.SCP_B_TargetTouchTime_ms = 11008;
lfp_tfa_states.SCP_A_InitialFixationOnsetTime_ms = 11009;
lfp_tfa_states.SCP_B_InitialFixationOnsetTime_ms = 11010;
lfp_tfa_states.SCP_A_TargetOnsetTime_ms = 11011;
lfp_tfa_states.SCP_B_TargetOnsetTime_ms = 11012;
lfp_tfa_states.SCP_A_GoSignalTime_ms = 11013;
lfp_tfa_states.SCP_B_GoSignalTime_ms = 11014;
lfp_tfa_states.SCP_A_TargetOffsetTime_ms = 11015;
lfp_tfa_states.SCP_B_TargetOffsetTime_ms = 11016;
lfp_tfa_states.SCP_A_RewardTrainOnsetTime_TDT_ms = 11017;
lfp_tfa_states.SCP_B_RewardTrainOnsetTime_TDT_ms = 11018;
lfp_tfa_states.SCP_FIRST_InitialFixationReleaseTime_ms = 11019;
lfp_tfa_states.SCP_SECOND_InitialFixationReleaseTime_ms = 11020;
lfp_tfa_states.SCP_FIRST_TargetTouchTime_ms = 11021;
lfp_tfa_states.SCP_SECOND_TargetTouchTime_ms = 11022;
lfp_tfa_states.SCP_FIRST_GoSignalTime_ms = 11023;
lfp_tfa_states.SCP_SECOND_GoSignalTime_ms = 11024;


